setono_sylius_catalog_promotions_admin_promotion:
    resource: |
        alias: setono_sylius_catalog_promotions.promotion
        path: catalog-promotions
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show']
        redirect: update
        grid: setono_sylius_catalog_promotions_admin_promotion
        permission: true
        vars:
            all:
                subheader: setono_sylius_catalog_promotions.ui.manage_promotions
                templates:
                    form: "@SetonoSyliusCatalogPromotionsPlugin/Admin/Promotion/_form.html.twig"
            index:
                icon: in cart
            update:
                templates:
                    form: "@SetonoSyliusCatalogPromotionsPlugin/Admin/Promotion/_form.html.twig"
    type: sylius.resource
