# Routes (listed for better navigation):
# - setono_sylius_bulk_discount_admin_discount_index
# - setono_sylius_bulk_discount_admin_discount_create
# - setono_sylius_bulk_discount_admin_discount_update
# - setono_sylius_bulk_discount_admin_discount_bulk_delete
# - setono_sylius_bulk_discount_admin_discount_delete

setono_sylius_bulk_discount_admin_discount:
    resource: |
        alias: setono_sylius_bulk_discount.discount
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show']
        redirect: update
        grid: setono_sylius_bulk_discount_admin_discount
        permission: true
        vars:
            all:
                subheader: setono_sylius_bulk_discount.ui.manage_discounts
                templates:
                    form: "@SetonoSyliusBulkDiscountPlugin/Admin/Discount/_form.html.twig"
            index:
                icon: in cart
            update:
                templates:
                    form: "@SetonoSyliusBulkDiscountPlugin/Admin/Discount/_form.html.twig"
    type: sylius.resource

setono_sylius_bulk_discount_admin_discount_bulk_recalculate:
    path: /discounts/bulk-recalculate/checked
    methods: [GET,POST]
    defaults:
        _controller: setono_sylius_bulk_discount.controller.discount:bulkRecalculateAction
        _sylius:
            csrf_protection: false
            section: admin
            redirect: referer
            permission: true
            paginate: false
            repository:
                method: findById
                arguments: [$ids]

setono_sylius_bulk_discount_admin_product_bulk_recalculate:
    path: /products/bulk-recalculate/checked
    methods: [GET,POST]
    defaults:
        _controller: sylius.controller.product:bulkRecalculateAction
        _sylius:
            csrf_protection: false
            section: admin
            redirect: referer
            permission: true
            paginate: false
            repository:
                method: findById
                arguments: [$ids]

setono_sylius_bulk_discount_admin_product_bulk_recalculate_all:
    path: /products/bulk-recalculate/all
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:bulkRecalculateAction
        _sylius:
            csrf_protection: false
            section: admin
            redirect: referer
            permission: true
            paginate: false
            repository:
                method: findAll

setono_sylius_bulk_discount_admin_product_bulk_reassign:
    path: /products/bulk-reassign/checked
    methods: [GET,POST]
    defaults:
        _controller: sylius.controller.product:bulkReassignAction
        _sylius:
            csrf_protection: false
            section: admin
            redirect: referer
            permission: true
            paginate: false
            repository:
                method: findById
                arguments: [$ids]

setono_sylius_bulk_discount_admin_product_bulk_reassign_all:
    path: /products/bulk-reassign/all
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:bulkReassignAction
        _sylius:
            csrf_protection: false
            section: admin
            redirect: referer
            permission: true
            paginate: false
            repository:
                method: findAll
