imports:
    - { resource: "@SetonoSyliusBulkSpecialsPlugin/Resources/config/grids/special.yaml" }

doctrine:
    orm:
        dql:
            numeric_functions:
                round: DoctrineExtensions\Query\Mysql\Round

framework:
    messenger:
        buses:
            setono_sylius_bulk_specials.command_bus: ~
