imports:
    - { resource: "@SetonoSyliusBulkDiscountPlugin/Resources/config/grids/discount.yaml" }

doctrine:
    orm:
        dql:
            numeric_functions:
                round: DoctrineExtensions\Query\Mysql\Round

framework:
    messenger:
        buses:
            setono_sylius_bulk_discount.command_bus: ~
