imports:
    - { resource: "@SetonoSyliusCatalogPromotionsPlugin/Resources/config/grids/promotion.yaml" }

doctrine:
    orm:
        dql:
            numeric_functions:
                round: DoctrineExtensions\Query\Mysql\Round
