imports:
    - { resource: "@SetonoSyliusBulkSpecialsPlugin/Resources/config/grids/special.yaml" }
    - { resource: "@SetonoSyliusBulkSpecialsPlugin/Resources/config/grids/product.yaml" }

framework:
    messenger:
        buses:
            setono_sylius_bulk_specials.command_bus: ~
